/* AXELAB · Daily challenges, practice routines and glossary. */
const DAILY = [
  { t: 'Pentatonic Explorer', d: 'Learn all five boxes of E minor pentatonic and connect them with slides. Spend two minutes in each box, then improvise moving between neighbors.', scaleId: 'pentatonic_minor', key: 4, tech: 'Slides + position shifts', tabc: 'E12 E15 A12 A14 D12 D14 G12 G14 B12 B15 e12 e15 /e17 e15 B17 B15 G14 G12:4', jam: { prog: 'aeolian_rock', key: 4, style: 'rock', scale: 'pentatonic_minor', bpm: 110 } },
  { t: 'Gilmour Tone Day', d: 'Play slowly. Every bend in tune before vibrato. Leave a full bar of silence between phrases. Thirty minutes, fewer notes than feels comfortable.', scaleId: 'pentatonic_minor', key: 11, tech: 'Bends + vibrato', tabc: 'G9b11~:4 G9b11r G7 D9:2 D7~:4', jam: { prog: 'aeolian_vamp', key: 11, style: 'ballad', scale: 'pentatonic_minor', bpm: 66 } },
  { t: 'Thrash Boot Camp', d: 'Alternate-picked chromatic runs and palm-muted gallops. Start at 80 bpm, raise 4 bpm each clean pass. Every note the same volume.', scaleId: 'phrygian', key: 4, tech: 'Alternate + down picking', tabc: 'E0:2 E0 E0 E1:2 E0 E0 | E0:2 E0 E0 E3 E1 E0:3', jam: { prog: 'phrygian_metal', key: 4, style: 'thrash', scale: 'phrygian', bpm: 160 } },
  { t: 'Dorian Groove', d: 'Play A Dorian over the i7–IV7 vamp. Land on F♯ (the 6th) every time the D7 arrives. Keep it funky and leave space.', scaleId: 'dorian', key: 9, tech: 'Rhythm-lead blending', tabc: 'G7+B7 G9+B8 G11+B10:2 G9+B8 G7+B7:2 G5+B5:4', jam: { prog: 'dorian_vamp', key: 9, style: 'funk', scale: 'dorian', bpm: 100 } },
  { t: 'Harmonic Minor Fire', d: 'A harmonic minor over Am–Dm–E7. Make the G♯ resolve to A every time the E7 hits. Try sweeping the E major arpeggio.', scaleId: 'harmonic_minor', key: 9, tech: 'Arpeggios + runs', tabc: 'A7 D6 D9 G9 B9 e7 e8 e7 B9 B10:4', jam: { prog: 'neoclassical', key: 9, style: 'metal', scale: 'harmonic_minor', bpm: 120 } },
  { t: 'Hendrix Chord Day', d: 'Thumb-over bass notes, 7♯9 stabs and double-stop fills over an E blues. Rhythm and lead in one part.', scaleId: 'blues', key: 4, allow: [8], tech: 'Double-stops + chord fills', tabc: 'A7+D6+G7+B8:2 A7+D6+G7+B8:2 B3 pB0 G2 pG0 D2:2 E0~:4', jam: { prog: 'blues12_quick', key: 4, style: 'blues_shuffle', scale: 'blues', bpm: 100 } },
  { t: 'Sweep Arpeggio Day', d: 'Three-string minor and major shapes at a slow tempo. One motion per direction, no notes ringing together.', scaleId: 'aeolian', key: 9, tech: 'Sweep picking', tabc: 'G14 B13 e12 B13 G14 B13 e12 B13 G14:3', jam: { prog: 'metal_minor', key: 9, style: 'metal', scale: 'aeolian', bpm: 120 } },
  { t: 'Chord-Tone Day', d: 'Over the ii–V–I, play only chord tones for 5 minutes. Then add scale notes between them, always landing on a chord tone on beat 1.', scaleId: 'ionian', key: 0, tech: 'Arpeggios + targeting', tabc: 'A5 A8 D7 G5 | E3 A2 A5 D3 | A3 D2 D5 G4:4', jam: { prog: 'ii_V_I', key: 0, style: 'jazz_swing', scale: 'ionian', bpm: 110, follow: 'chordtones' } },
  { t: 'Major Pentatonic Country', d: 'A major pentatonic over a train beat. Bend the 2 up to the 3, add the ♭3 as a passing note, hybrid-pick double-stops.', scaleId: 'pentatonic_major', key: 9, tech: 'Hybrid picking', tabc: 'G2 G4b6 B2 B5 e2 e5:4', jam: { prog: 'country_train', key: 9, style: 'country', scale: 'pentatonic_major', bpm: 140 } },
  { t: 'Modal Color Tour', d: 'Five minutes each over the Lydian, Mixolydian, Dorian and Phrygian vamps. Lean on each character note until you can hear it with your eyes closed.', scaleId: 'lydian', key: 5, tech: 'Modal phrasing', tabc: 'e7 e8 e10 B8 B10 e7:4', jam: { prog: 'lydian_vamp', key: 5, style: 'ballad', scale: 'lydian', bpm: 80 } },
  { t: 'Rhythm Section Day', d: 'Mute the rhythm guitar in the Jam mixer and play it yourself: funk scratches, then reggae skanks, then a shuffle. Lock to the kick and snare.', scaleId: 'mixolydian', key: 4, tech: 'Muting + groove', tabc: 'D6+G7+B7 Dx+Gx+Bx Dx+Gx+Bx D6+G7+B7 Dx+Gx+Bx D6+G7+B7 Dx+Gx+Bx Dx+Gx+Bx', jam: { prog: 'funk_vamp', key: 4, style: 'funk', scale: 'pentatonic_minor', bpm: 100 } },
  { t: 'Follow the Changes', d: 'Turn on chord-scale view in the Jam tab over the G–B–C–Cm progression. Find the one note that changes for each chord and make it the center of a phrase.', scaleId: 'ionian', key: 7, allow: [3], tech: 'Chord-scale switching', tabc: 'B3:4 | B4:4 | B5:4 | B4:4', cap: 'D over G, D♯ over B, E over C, E♭ over Cm: the note that moves.', jam: { prog: 'modal_mix', key: 7, style: 'ballad', scale: 'ionian', bpm: 84, follow: 'chord' } },
  { t: 'Three-Note Solo', d: 'Solo over the minor blues using only A, C and D. Make it musical with rhythm, bends, vibrato and space. Then add one note at a time.', scaleId: 'pentatonic_minor', key: 9, tech: 'Phrasing', tabc: 'e8b10~:3 e5 B8:2 - - | e8b10~:3 e5 B8 B5:2', jam: { prog: 'minor_blues', key: 9, style: 'slow_blues', scale: 'pentatonic_minor', bpm: 62 } },
  { t: 'All Twelve Keys', d: 'Turn on key cycling (up a 4th every loop) over the 12-bar blues. Play box 1 of minor pentatonic in every key without stopping.', scaleId: 'pentatonic_minor', key: 9, tech: 'Fretboard knowledge', tabc: 'E5 E8 A5 A7 D5 D7 G5 G7 B5 B8 e5 e8:3', jam: { prog: 'blues12', key: 9, style: 'blues_shuffle', scale: 'pentatonic_minor', bpm: 96, cycle: 'fourths' } }
];

const ROUTINES = [
  { id: 'starter', name: 'Starter (20 min)', blocks: [['Warm-up: chromatic & stretches', 3, 'technique:Alternate Picking'], ['Chord changes (one-minute changes)', 5, 'lesson:open-chords'], ['Scale: minor pentatonic box 1', 5, 'lesson:pent-minor'], ['Jam: 12-bar blues', 5, 'jam:blues12'], ['Ear: intervals', 2, 'ear:intervals']] },
  { id: 'improviser', name: 'Improviser (45 min)', blocks: [['Warm-up', 5, 'technique:Alternate Picking'], ['Technique of the week', 10, 'technique'], ['Vocabulary: one lick in 3 keys', 10, 'artists'], ['Improvise with chord-scale view', 10, 'jam'], ['Ear: scale degrees', 5, 'ear:degrees'], ['Review & log', 5, 'log']] },
  { id: 'shred', name: 'Technique Builder (40 min)', blocks: [['Warm-up chromatic', 5, 'technique:Speed Building'], ['Alternate picking sequences', 10, 'technique:Alternate Picking'], ['Legato 3nps', 8, 'technique:Legato'], ['Sweeps', 8, 'technique:Sweep Picking'], ['Apply over metal jam', 9, 'jam:metal_minor']] },
  { id: 'theory', name: 'Theory in Practice (30 min)', blocks: [['Diatonic chords in a new key', 8, 'theory:harmony'], ['Arpeggios over ii–V–I', 8, 'lesson:arpeggios'], ['Modes over vamps', 9, 'lesson:modes'], ['Ear: chord quality', 5, 'ear:chords']] }
];

const GLOSSARY = [
  ['Accidental', 'A sharp (♯), flat (♭) or natural (♮) that raises or lowers a note.'],
  ['Arpeggio', 'The notes of a chord played one at a time.'],
  ['Bar (measure)', 'A group of beats, set by the time signature.'],
  ['Barre chord', 'A chord where one finger presses several strings across a fret.'],
  ['Blue note', 'A note bent or played between major and minor: the ♭3, ♭5 or ♭7 against a major chord.'],
  ['bpm', 'Beats per minute: the tempo.'],
  ['CAGED', 'A system of five moveable chord shapes (C, A, G, E, D) that map the neck.'],
  ['Character note', 'The note that makes a mode sound different from plain major or minor.'],
  ['Chord tone', 'A note that belongs to the current chord (root, 3rd, 5th, 7th…).'],
  ['Chord scale', 'A scale chosen to match one specific chord.'],
  ['Chromatic', 'Moving by half steps; using notes outside the key.'],
  ['Circle of fifths', 'The 12 keys arranged by perfect 5ths, showing how keys relate.'],
  ['Diatonic', 'Belonging to the key: using only the notes of its scale.'],
  ['Dominant', 'The V chord, or any 7th chord built 1-3-5-♭7, which pulls toward resolution.'],
  ['Double-stop', 'Two notes played together.'],
  ['Drop D', 'Tuning the low E string down a whole step to D.'],
  ['Guide tones', 'The 3rd and 7th of a chord, which define its quality.'],
  ['Half step', 'One fret; the smallest interval in Western music.'],
  ['Interval', 'The distance between two notes.'],
  ['Inversion', 'A chord with a note other than the root in the bass.'],
  ['Key', 'A tonal center and its family of notes and chords.'],
  ['Leading tone', 'The 7th degree, a half step below the root, which pulls up to it.'],
  ['Legato', 'Smooth, connected playing; on guitar, mostly hammer-ons and pull-offs.'],
  ['Mode', 'A scale formed by starting another scale from a different degree.'],
  ['Modal interchange', 'Borrowing chords from a parallel key or mode.'],
  ['Octave', 'The same note at double (or half) the frequency, 12 frets apart.'],
  ['Palm mute', 'Resting the picking palm at the bridge for a short, percussive sound.'],
  ['Parallel key', 'Major and minor keys with the same root (C major and C minor).'],
  ['Pentatonic', 'A five-note scale.'],
  ['Power chord', 'A root and 5th, without a 3rd.'],
  ['Relative key', 'Major and minor keys with the same notes (C major and A minor).'],
  ['Resolution', 'Moving from tension to stability.'],
  ['Riff', 'A short repeated musical figure, often the hook of a song.'],
  ['Root', 'The note a chord or scale is named after.'],
  ['Scale degree', 'A note’s position in the scale, numbered from the root.'],
  ['Secondary dominant', 'A dominant chord that resolves to a chord other than I.'],
  ['Shuffle', 'A swung, triplet-based rhythmic feel.'],
  ['Swing', 'Playing 8th notes long-short.'],
  ['Syncopation', 'Accents placed off the main beats.'],
  ['Tension', 'A note or chord that wants to move somewhere else.'],
  ['Time signature', 'Beats per bar (top) and the note value of a beat (bottom).'],
  ['Tonic', 'The home note or chord of a key.'],
  ['Tritone', 'An interval of three whole steps (6 frets); very unstable.'],
  ['Tritone substitution', 'Replacing a dominant chord with the dominant a tritone away.'],
  ['Turnaround', 'A short progression at the end of a section that leads back to the top.'],
  ['Voice leading', 'Moving each note of a chord the shortest distance to the next chord.'],
  ['Voicing', 'The specific arrangement of a chord’s notes on the instrument.'],
  ['Whole step', 'Two frets.']
];
if (typeof module !== 'undefined') module.exports = { list: DAILY, DAILY: DAILY, ROUTINES: ROUTINES, GLOSSARY: GLOSSARY };
